# Generated by Django 4.2.18 on 2025-02-15 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GA4WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('cityId', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('deviceCategory', models.CharField(blank=True, max_length=225, null=True)),
                ('pagePath', models.CharField(blank=True, max_length=100, null=True)),
                ('pagePathPlusQueryString', models.CharField(blank=True, max_length=200, null=True)),
                ('pageTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('startDate', models.CharField(blank=True, max_length=50, null=True)),
                ('endDate', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_google_ga4_webpage', to='social_auth.socialuser')),
            ],
            options={
                'db_table': 'google_ga4_webpage',
            },
        ),
        migrations.CreateModel(
            name='GA4Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('deviceCategory', models.CharField(blank=True, max_length=225, null=True)),
                ('firstUserSourceMedium', models.CharField(blank=True, max_length=225, null=True)),
                ('sessionSource', models.CharField(blank=True, max_length=225, null=True)),
                ('sessions', models.IntegerField(blank=True, null=True)),
                ('activeusers', models.IntegerField(blank=True, null=True)),
                ('newUsers', models.IntegerField(blank=True, null=True)),
                ('totalUsers', models.IntegerField(blank=True, null=True)),
                ('bounceRate', models.FloatField(blank=True, null=True)),
                ('averageSessionDuration', models.FloatField(blank=True, null=True)),
                ('eventCount', models.IntegerField(blank=True, null=True)),
                ('conversions', models.IntegerField(blank=True, null=True)),
                ('screenPageViews', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_google_ga4_session', to='social_auth.socialuser')),
            ],
            options={
                'db_table': 'google_ga4_session',
            },
        ),
        migrations.CreateModel(
            name='GA4Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('deviceCategory', models.CharField(blank=True, max_length=225, null=True)),
                ('firstUserSourceMedium', models.CharField(blank=True, max_length=225, null=True)),
                ('sessionSource', models.CharField(blank=True, max_length=225, null=True)),
                ('pagePath', models.CharField(blank=True, max_length=100, null=True)),
                ('pageTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('eventName', models.CharField(blank=True, max_length=50, null=True)),
                ('sessions', models.IntegerField(blank=True, null=True)),
                ('activeusers', models.IntegerField(blank=True, null=True)),
                ('newUsers', models.IntegerField(blank=True, null=True)),
                ('totalUsers', models.IntegerField(blank=True, null=True)),
                ('bounceRate', models.FloatField(blank=True, null=True)),
                ('averageSessionDuration', models.FloatField(blank=True, null=True)),
                ('eventCount', models.IntegerField(blank=True, null=True)),
                ('conversions', models.IntegerField(blank=True, null=True)),
                ('screenPageViews', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_google_ga4_event', to='social_auth.socialuser')),
            ],
            options={
                'db_table': 'google_ga4_event',
            },
        ),
    ]
