# Generated by Django 5.0.10 on 2025-02-19 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_app', '0001_initial'),
        ('social_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ga4session',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ga4webpage',
            name='user',
        ),
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('expiry', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_user', to='social_auth.socialuser')),
            ],
            options={
                'verbose_name_plural': 'Google Credentials',
            },
        ),
        migrations.DeleteModel(
            name='GA4Event',
        ),
        migrations.DeleteModel(
            name='GA4Session',
        ),
        migrations.DeleteModel(
            name='GA4WebPage',
        ),
    ]
