# Generated by Django 5.1.4 on 2025-01-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GA4Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('deviceCategory', models.CharField(max_length=50)),
                ('firstUserSourceMedium', models.CharField(max_length=50)),
                ('sessionSource', models.CharField(max_length=50)),
                ('pagePath', models.CharField(max_length=100)),
                ('pageTitle', models.CharField(max_length=100)),
                ('eventName', models.CharField(max_length=50)),
                ('sessions', models.IntegerField()),
                ('activeusers', models.IntegerField()),
                ('newUsers', models.IntegerField()),
                ('totalUsers', models.IntegerField()),
                ('bounceRate', models.FloatField()),
                ('averageSessionDuration', models.FloatField()),
                ('eventCount', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('screenPageViews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GA4Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('deviceCategory', models.CharField(max_length=50)),
                ('firstUserSourceMedium', models.CharField(max_length=50)),
                ('sessionSource', models.CharField(max_length=50)),
                ('sessions', models.IntegerField()),
                ('activeusers', models.IntegerField()),
                ('newUsers', models.IntegerField()),
                ('totalUsers', models.IntegerField()),
                ('bounceRate', models.FloatField()),
                ('averageSessionDuration', models.FloatField()),
                ('eventCount', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('screenPageViews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GA4WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('cityId', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('deviceCategory', models.CharField(max_length=50)),
                ('pagePath', models.CharField(max_length=100)),
                ('pagePathPlusQueryString', models.CharField(max_length=200)),
                ('pageTitle', models.CharField(max_length=100)),
                ('startDate', models.CharField(max_length=50)),
                ('endDate', models.CharField(max_length=50)),
            ],
        ),
    ]
