# Generated by Django 5.0.11 on 2025-01-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictaCustomer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('plandet', models.CharField(max_length=255)),
                ('costdet', models.CharField(max_length=255)),
                ('validity', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('plantype', models.CharField(max_length=255)),
                ('users', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=20)),
                ('cnameid', models.CharField(max_length=255)),
                ('logourl', models.URLField(max_length=500)),
                ('themetype', models.CharField(max_length=255)),
                ('custome_added', models.DateField(blank=True, null=True)),
                ('auzureid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'predicta_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FB_Oauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('page_id', models.CharField(max_length=255)),
                ('ad_account_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'db_table': 'FB_Oauth',
            },
        ),
        migrations.CreateModel(
            name='FBInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
                ('page_fans', models.IntegerField(null=True)),
                ('page_fan_adds', models.IntegerField(null=True)),
                ('page_fan_removes', models.IntegerField(null=True)),
                ('page_views_total', models.IntegerField(null=True)),
                ('page_video_views', models.IntegerField(null=True)),
                ('page_video_view_time', models.IntegerField(null=True)),
                ('page_video_views_paid', models.IntegerField(null=True)),
                ('page_video_views_organic', models.IntegerField(null=True)),
                ('page_video_views_click_to_play', models.IntegerField(null=True)),
                ('page_posts_impressions', models.IntegerField(null=True)),
                ('page_posts_impressions_paid', models.IntegerField(null=True)),
                ('page_posts_impressions_organic', models.IntegerField(null=True)),
                ('page_posts_impressions_viral', models.IntegerField(null=True)),
                ('page_posts_impressions_nonviral', models.IntegerField(null=True)),
                ('page_impressions', models.IntegerField(null=True)),
                ('page_impressions_unique', models.IntegerField(null=True)),
                ('page_impressions_paid', models.IntegerField(null=True)),
                ('page_impressions_viral', models.IntegerField(null=True)),
                ('page_impressions_nonviral', models.IntegerField(null=True)),
                ('page_impressions_organic_v2', models.IntegerField(null=True)),
                ('page_post_engagements', models.IntegerField(null=True)),
                ('page_actions_post_reactions_like_total', models.IntegerField(null=True)),
                ('page_actions_post_reactions_anger_total', models.IntegerField(null=True)),
                ('page_actions_post_reactions_wow_total', models.IntegerField(null=True)),
                ('page_actions_post_reactions_haha_total', models.IntegerField(null=True)),
                ('page_actions_post_reactions_love_total', models.IntegerField(null=True)),
                ('page_actions_post_reactions_sorry_total', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'FB_Insights_KS',
            },
        ),
    ]
