# Generated by Django 4.2.18 on 2025-02-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fb_oauth',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
