# Generated by Django 4.2.18 on 2025-02-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0002_alter_fb_oauth_access_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictaCustomer',
        ),
    ]
