# Generated by Django 5.0.10 on 2025-02-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0003_delete_predictacustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fb_oauth',
            name='ad_accounts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fb_oauth',
            name='business_profiles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fb_oauth',
            name='instagram_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fb_oauth',
            name='page_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
