# Generated by Django 5.0.10 on 2025-02-20 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0005_delete_fb_oauth'),
        ('social_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FB_Oauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_account', models.CharField(blank=True, max_length=255, null=True)),
                ('business_profiles', models.JSONField(blank=True, null=True)),
                ('ad_accounts', models.CharField(blank=True, max_length=255, null=True)),
                ('social_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_FB_Oauth', to='social_auth.socialuser')),
            ],
            options={
                'db_table': 'FB_Oauth',
            },
        ),
    ]
