# Generated by Django 5.0.10 on 2025-02-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0007_alter_fb_oauth_business_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookcampaigninsight',
            name='social_user',
        ),
        migrations.RemoveField(
            model_name='facebookfollowersbycity',
            name='social_user',
        ),
        migrations.RemoveField(
            model_name='facebookfollowersinsight',
            name='social_user',
        ),
        migrations.RemoveField(
            model_name='facebookinsights',
            name='social_user',
        ),
        migrations.RemoveField(
            model_name='fbadsinsight',
            name='social_user',
        ),
        migrations.RemoveField(
            model_name='fbadsinsightagegender',
            name='social_user',
        ),
        migrations.RemoveField(
            model_name='fbadsinsightbydevice',
            name='social_user',
        ),
        migrations.RemoveField(
            model_name='fbadsinsightbylocation',
            name='social_user',
        ),
    ]
