# Generated by Django 5.0.10 on 2025-02-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0008_remove_facebookcampaigninsight_social_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookCampaignInsight',
        ),
        migrations.DeleteModel(
            name='FacebookFollowersbycity',
        ),
        migrations.DeleteModel(
            name='FacebookFollowersInsight',
        ),
        migrations.DeleteModel(
            name='FacebookInsights',
        ),
        migrations.DeleteModel(
            name='FBAdsInsight',
        ),
        migrations.DeleteModel(
            name='FBAdsInsightAgeGender',
        ),
        migrations.DeleteModel(
            name='FBAdsInsightByDevice',
        ),
        migrations.DeleteModel(
            name='FBAdsInsightByLocation',
        ),
    ]
