# Generated by Django 5.0.10 on 2025-02-20 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0010_facebookcampaigninsight_facebookfollowersbycity_and_more'),
        ('social_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcampaigninsight',
            name='social_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_FB_Campaign_insigths', to='social_auth.socialuser'),
        ),
        migrations.AddField(
            model_name='facebookfollowersbycity',
            name='social_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_FB_Followers_by_city', to='social_auth.socialuser'),
        ),
        migrations.AddField(
            model_name='facebookfollowersinsight',
            name='social_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_FB_Followers_statistics', to='social_auth.socialuser'),
        ),
        migrations.AddField(
            model_name='facebookinsights',
            name='social_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_FB_Insights', to='social_auth.socialuser'),
        ),
        migrations.AddField(
            model_name='fbadsinsight',
            name='social_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_FB_Ads_Insights', to='social_auth.socialuser'),
        ),
        migrations.AddField(
            model_name='fbadsinsightagegender',
            name='social_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_FB_Ads_Insights_by_age_gender', to='social_auth.socialuser'),
        ),
        migrations.AddField(
            model_name='fbadsinsightbydevice',
            name='social_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_FB_Ads_Insights_by_device', to='social_auth.socialuser'),
        ),
        migrations.AddField(
            model_name='fbadsinsightbylocation',
            name='social_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_FB_Ads_Insights_by_location', to='social_auth.socialuser'),
        ),
    ]
