# Generated by Django 4.2.18 on 2025-02-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPageStatisticsLifetime',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('followers_count', models.CharField(max_length=50)),
                ('follows_count', models.CharField(max_length=50)),
                ('media_count', models.CharField(max_length=50)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture_url', models.CharField(max_length=500)),
                ('biography', models.CharField(max_length=2000)),
                ('created_at', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('data_created_date', models.DateField(auto_now_add=True)),
                ('data_created_time', models.TimeField(auto_now_add=True)),
                ('social_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_Instagram_Page_Statistics_Lifetime', to='social_auth.socialuser')),
            ],
            options={
                'db_table': 'Instagram_Page_Statistics_Lifetime',
            },
        ),
        migrations.CreateModel(
            name='InstagramPageInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField()),
                ('follower_count', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('page_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('data_created_date', models.DateField(auto_now_add=True)),
                ('data_created_time', models.TimeField(auto_now_add=True)),
                ('social_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_Instagram_Page_Insight', to='social_auth.socialuser')),
            ],
            options={
                'db_table': 'Instagram_Page_Insight',
            },
        ),
        migrations.CreateModel(
            name='InstagramMediaInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ig_id', models.CharField(max_length=50, unique=True, verbose_name='Instagram Post ID')),
                ('post_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Date')),
                ('email', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=50, verbose_name='Media Type')),
                ('comments_count', models.CharField(default='0', max_length=20, verbose_name='Comments Count')),
                ('like_count', models.CharField(default='0', max_length=20, verbose_name='Like Count')),
                ('permalink', models.CharField(max_length=500, verbose_name='Permalink')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('media_product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Media Product Type')),
                ('is_comment_enabled', models.CharField(default='True', max_length=10, verbose_name='Comments Enabled')),
                ('media_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Media URL')),
                ('impressions', models.CharField(default='0', max_length=20, verbose_name='Impressions')),
                ('reach', models.CharField(default='0', max_length=20, verbose_name='Reach')),
                ('profile_visits', models.CharField(default='0', max_length=20, verbose_name='Profile Visits')),
                ('profile_activity', models.CharField(default='0', max_length=20, verbose_name='Profile Activity')),
                ('replies', models.CharField(default='0', max_length=20, verbose_name='Replies')),
                ('saved', models.CharField(default='0', max_length=20, verbose_name='Saved')),
                ('video_views', models.CharField(default='0', max_length=20, verbose_name='Video Views')),
                ('shares', models.CharField(default='0', max_length=20, verbose_name='Shares')),
                ('total_interactions', models.CharField(default='0', max_length=20, verbose_name='Total Interactions')),
                ('follows', models.CharField(default='0', max_length=20, verbose_name='Follows')),
                ('created_at', models.CharField(max_length=100, verbose_name='Created At')),
                ('updated_at', models.CharField(max_length=100, verbose_name='Updated At')),
                ('data_created_date', models.CharField(max_length=255)),
                ('data_created_time', models.CharField(max_length=255)),
                ('social_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_Instagram_Media_Insights', to='social_auth.socialuser')),
            ],
            options={
                'db_table': 'Instagram_Media_Insights',
            },
        ),
    ]
