# Generated by Django 5.0.10 on 2025-02-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrammediainsight',
            name='social_user',
        ),
        migrations.RemoveField(
            model_name='instagrampageinsight',
            name='social_user',
        ),
        migrations.RemoveField(
            model_name='instagrampagestatisticslifetime',
            name='social_user',
        ),
    ]
