# Generated by Django 4.2.18 on 2025-02-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='comments_count',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Comments Count'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='created_at',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='data_created_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='data_created_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='follows',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Follows'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='impressions',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Impressions'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='is_comment_enabled',
            field=models.CharField(blank=True, default='True', max_length=10, null=True, verbose_name='Comments Enabled'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='like_count',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Like Count'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Media Type'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='permalink',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Permalink'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='profile_activity',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Profile Activity'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='reach',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Reach'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='replies',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Replies'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='saved',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Saved'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='shares',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Shares'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='total_interactions',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Total Interactions'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='updated_at',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='video_views',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Video Views'),
        ),
        migrations.AlterField(
            model_name='instagrampageinsight',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampageinsight',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampageinsight',
            name='follower_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampageinsight',
            name='impressions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampageinsight',
            name='page_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampageinsight',
            name='reach',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampagestatisticslifetime',
            name='biography',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampagestatisticslifetime',
            name='created_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampagestatisticslifetime',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampagestatisticslifetime',
            name='followers_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampagestatisticslifetime',
            name='follows_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampagestatisticslifetime',
            name='media_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampagestatisticslifetime',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampagestatisticslifetime',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampagestatisticslifetime',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
