# Generated by Django 5.0.10 on 2025-02-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instagram', '0003_delete_instagrammediainsight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramMediaInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ig_id', models.CharField(max_length=50, unique=True, verbose_name='Instagram Post ID')),
                ('post_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Date')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Media Type')),
                ('comments_count', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Comments Count')),
                ('like_count', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Like Count')),
                ('permalink', models.CharField(blank=True, max_length=500, null=True, verbose_name='Permalink')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('media_product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Media Product Type')),
                ('is_comment_enabled', models.CharField(blank=True, default='True', max_length=10, null=True, verbose_name='Comments Enabled')),
                ('media_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Media URL')),
                ('impressions', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Impressions')),
                ('reach', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Reach')),
                ('profile_visits', models.CharField(default='0', max_length=20, verbose_name='Profile Visits')),
                ('profile_activity', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Profile Activity')),
                ('replies', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Replies')),
                ('saved', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Saved')),
                ('video_views', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Video Views')),
                ('shares', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Shares')),
                ('total_interactions', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Total Interactions')),
                ('follows', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Follows')),
                ('created_at', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created At')),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated At')),
                ('data_created_date', models.CharField(blank=True, max_length=255, null=True)),
                ('data_created_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Instagram_Media_Insights',
            },
        ),
        migrations.CreateModel(
            name='InstagramPageInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('follower_count', models.IntegerField(blank=True, default=0, null=True)),
                ('impressions', models.IntegerField(blank=True, default=0, null=True)),
                ('reach', models.IntegerField(blank=True, default=0, null=True)),
                ('page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_created_date', models.DateField(auto_now_add=True)),
                ('data_created_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Instagram_Page_Insight',
            },
        ),
        migrations.CreateModel(
            name='InstagramPageStatisticsLifetime',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('followers_count', models.CharField(blank=True, max_length=50, null=True)),
                ('follows_count', models.CharField(blank=True, max_length=50, null=True)),
                ('media_count', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture_url', models.CharField(blank=True, max_length=500, null=True)),
                ('biography', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_created_date', models.DateField(auto_now_add=True)),
                ('data_created_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Instagram_Page_Statistics_Lifetime',
            },
        ),
    ]
