# Generated by Django 4.2.18 on 2025-02-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0001_initial'),
        ('instagram', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammediainsight',
            name='social_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_Instagram_Media_Insights', to='social_auth.socialuser'),
        ),
        migrations.AddField(
            model_name='instagrampagestatisticslifetime',
            name='social_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_Instagram_Page_Statistics_Lifetime', to='social_auth.socialuser'),
        ),
    ]
