# Generated by Django 5.0.10 on 2025-02-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_remove_instagrammediainsight_social_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramMediaInsight',
        ),
        migrations.DeleteModel(
            name='InstagramPageInsight',
        ),
        migrations.DeleteModel(
            name='InstagramPageStatisticsLifetime',
        ),
    ]
