# Generated by Django 5.0.10 on 2025-02-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='media_url',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Media URL'),
        ),
    ]
