# Generated by Django 4.2.18 on 2025-02-05 19:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_in', models.CharField(blank=True, max_length=520, null=True)),
                ('social_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_linkedin_auth', to='social_auth.socialuser')),
            ],
            options={
                'db_table': 'Linkedin_auth',
            },
        ),
        migrations.CreateModel(
            name='LinkedinSeniorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('load_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('urn', models.CharField(blank=True, max_length=32, null=True)),
                ('seniority_id', models.BigIntegerField(blank=True, null=True)),
                ('seniority_name', models.CharField(blank=True, max_length=16, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_linkedin_seniorities', to='linkedin_app.linkedinauth')),
            ],
            options={
                'db_table': 'Linkedin_Seniorities',
            },
        ),
        migrations.CreateModel(
            name='LinkedinRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('locale_country', models.CharField(blank=True, max_length=4, null=True)),
                ('locale_language', models.CharField(blank=True, max_length=4, null=True)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=32, null=True)),
                ('region_id', models.BigIntegerField(blank=True, null=True)),
                ('urn', models.CharField(blank=True, max_length=32, null=True)),
                ('states', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_linkedin_regions', to='linkedin_app.linkedinauth')),
            ],
            options={
                'db_table': 'Linkedin_Regions',
            },
        ),
        migrations.CreateModel(
            name='LinkedinPostsStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('load_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('organizational_entity', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('commentary', models.TextField(blank=True, null=True)),
                ('is_reshare_disabled_by_author', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('lifecycle_state', models.CharField(blank=True, max_length=50, null=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, max_length=50, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('feed_distribution', models.CharField(blank=True, max_length=50, null=True)),
                ('is_edited_by_author', models.CharField(blank=True, max_length=10, null=True)),
                ('unique_impressions_count', models.IntegerField(blank=True, null=True)),
                ('share_count', models.IntegerField(blank=True, null=True)),
                ('engagement', models.IntegerField(blank=True, null=True)),
                ('click_count', models.IntegerField(blank=True, null=True)),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('impression_count', models.IntegerField(blank=True, null=True)),
                ('engagement_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('click_through_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_linkedin_posts_statistics', to='linkedin_app.linkedinauth')),
            ],
            options={
                'db_table': 'Linkedin_Posts_Statistics',
            },
        ),
        migrations.CreateModel(
            name='LinkedinLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('load_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('urn', models.CharField(blank=True, max_length=25, null=True)),
                ('geo_id', models.BigIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_linkedin_location', to='linkedin_app.linkedinauth')),
            ],
            options={
                'db_table': 'Linkedin_Location',
            },
        ),
        migrations.CreateModel(
            name='LinkedinIndustries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('load_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('urn', models.CharField(blank=True, max_length=32, null=True)),
                ('industry_id', models.BigIntegerField(blank=True, null=True)),
                ('industry_name', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_linkedin_industries', to='linkedin_app.linkedinauth')),
            ],
            options={
                'db_table': 'Linkedin_Industries',
            },
        ),
        migrations.CreateModel(
            name='LinkedinFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('load_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('urn', models.CharField(blank=True, max_length=32, null=True)),
                ('function_id', models.BigIntegerField(blank=True, null=True)),
                ('function_name', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_linkedin_functions', to='linkedin_app.linkedinauth')),
            ],
            options={
                'db_table': 'Linkedin_Functions',
            },
        ),
        migrations.CreateModel(
            name='LinkedinFollowersGainStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('load_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('organic_follower_gain', models.BigIntegerField(blank=True, null=True)),
                ('paid_follower_gain', models.BigIntegerField(blank=True, null=True)),
                ('organizational_entity', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_linkedin_followersGain_statistics', to='linkedin_app.linkedinauth')),
            ],
            options={
                'db_table': 'Linkedin_FollowersGain_Statistics',
            },
        ),
        migrations.CreateModel(
            name='LinkedinFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('load_datetime', models.DateTimeField(blank=True, null=True)),
                ('organic_follower_count', models.IntegerField(blank=True, null=True)),
                ('paid_follower_count', models.IntegerField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, max_length=50, null=True)),
                ('data_type_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_linkedin_followers', to='linkedin_app.linkedinauth')),
            ],
            options={
                'db_table': 'Linkedin_Followers',
            },
        ),
        migrations.CreateModel(
            name='LinkedinCountryGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('load_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('urn', models.CharField(blank=True, max_length=32, null=True)),
                ('locale_country', models.CharField(blank=True, max_length=4, null=True)),
                ('locale_language', models.CharField(blank=True, max_length=4, null=True)),
                ('country_group', models.CharField(blank=True, max_length=16, null=True)),
                ('country_group_code', models.CharField(blank=True, max_length=4, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_linkedin_country_groups', to='linkedin_app.linkedinauth')),
            ],
            options={
                'db_table': 'Linkedin_Country_Groups',
            },
        ),
        migrations.CreateModel(
            name='LinkedinCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('load_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('locale_country', models.CharField(max_length=4, null=True)),
                ('locale_language', models.CharField(max_length=4, null=True)),
                ('country_name', models.CharField(max_length=64, null=True)),
                ('country_group', models.CharField(max_length=32, null=True)),
                ('urn', models.CharField(max_length=32, null=True)),
                ('country_code', models.CharField(max_length=4, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_linkedin_countries', to='linkedin_app.linkedinauth')),
            ],
            options={
                'db_table': 'Linkedin_Countries',
            },
        ),
    ]
